//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIVLauncher.Core.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("XIVLauncher.Core.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EnterYourOTP {
            get {
                return ResourceManager.GetString("EnterYourOTP", resourceCulture);
            }
        }
        
        internal static string OKLabel {
            get {
                return ResourceManager.GetString("OKLabel", resourceCulture);
            }
        }
        
        internal static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        internal static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        internal static string SearchForSettings {
            get {
                return ResourceManager.GetString("SearchForSettings", resourceCulture);
            }
        }
        
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        internal static string WineInstallSetting {
            get {
                return ResourceManager.GetString("WineInstallSetting", resourceCulture);
            }
        }
        
        internal static string WineInstallSettingDescription {
            get {
                return ResourceManager.GetString("WineInstallSettingDescription", resourceCulture);
            }
        }
        
        internal static string WineVersionSetting {
            get {
                return ResourceManager.GetString("WineVersionSetting", resourceCulture);
            }
        }
        
        internal static string WineVersionSettingDescription {
            get {
                return ResourceManager.GetString("WineVersionSettingDescription", resourceCulture);
            }
        }
        
        internal static string WineBinaryPathSetting {
            get {
                return ResourceManager.GetString("WineBinaryPathSetting", resourceCulture);
            }
        }
        
        internal static string WineBinarySettingDescription {
            get {
                return ResourceManager.GetString("WineBinarySettingDescription", resourceCulture);
            }
        }
        
        internal static string DXVKVersionSetting {
            get {
                return ResourceManager.GetString("DXVKVersionSetting", resourceCulture);
            }
        }
        
        internal static string DXVKVersionSettingDescription {
            get {
                return ResourceManager.GetString("DXVKVersionSettingDescription", resourceCulture);
            }
        }
        
        internal static string DXVKEnableAsyncSetting {
            get {
                return ResourceManager.GetString("DXVKEnableAsyncSetting", resourceCulture);
            }
        }
        
        internal static string DXVKEnableAsyncSettingDescription {
            get {
                return ResourceManager.GetString("DXVKEnableAsyncSettingDescription", resourceCulture);
            }
        }
        
        internal static string EnableFeralGameModeSetting {
            get {
                return ResourceManager.GetString("EnableFeralGameModeSetting", resourceCulture);
            }
        }
        
        internal static string EnableFeralGameModeSettingDescription {
            get {
                return ResourceManager.GetString("EnableFeralGameModeSettingDescription", resourceCulture);
            }
        }
        
        internal static string EnableFeralGameModeNotFoundValidation {
            get {
                return ResourceManager.GetString("EnableFeralGameModeNotFoundValidation", resourceCulture);
            }
        }
        
        internal static string EnableESyncSetting {
            get {
                return ResourceManager.GetString("EnableESyncSetting", resourceCulture);
            }
        }
        
        internal static string EnableFSyncSetting {
            get {
                return ResourceManager.GetString("EnableFSyncSetting", resourceCulture);
            }
        }
        
        internal static string EnableESyncSettingDescription {
            get {
                return ResourceManager.GetString("EnableESyncSettingDescription", resourceCulture);
            }
        }
        
        internal static string EnableFSyncSettingDescription {
            get {
                return ResourceManager.GetString("EnableFSyncSettingDescription", resourceCulture);
            }
        }
        
        internal static string EnableFSyncSettingMinKernelValidation {
            get {
                return ResourceManager.GetString("EnableFSyncSettingMinKernelValidation", resourceCulture);
            }
        }
        
        internal static string SetWindows7Setting {
            get {
                return ResourceManager.GetString("SetWindows7Setting", resourceCulture);
            }
        }
        
        internal static string SetWindows7SettingDescription {
            get {
                return ResourceManager.GetString("SetWindows7SettingDescription", resourceCulture);
            }
        }
        
        internal static string EnableDXVKOverlaySetting {
            get {
                return ResourceManager.GetString("EnableDXVKOverlaySetting", resourceCulture);
            }
        }
        
        internal static string EnableDXVKOverlaySettingDescription {
            get {
                return ResourceManager.GetString("EnableDXVKOverlaySettingDescription", resourceCulture);
            }
        }
        
        internal static string WineDebugAdditionalVarSetting {
            get {
                return ResourceManager.GetString("WineDebugAdditionalVarSetting", resourceCulture);
            }
        }
        
        internal static string WineDebugAdditionalVarSettingDescription {
            get {
                return ResourceManager.GetString("WineDebugAdditionalVarSettingDescription", resourceCulture);
            }
        }
        
        internal static string WineTitle {
            get {
                return ResourceManager.GetString("WineTitle", resourceCulture);
            }
        }
        
        internal static string CompatibilityToolNotSetup {
            get {
                return ResourceManager.GetString("CompatibilityToolNotSetup", resourceCulture);
            }
        }
        
        internal static string OpenWINEPrefix {
            get {
                return ResourceManager.GetString("OpenWINEPrefix", resourceCulture);
            }
        }
        
        internal static string OpenWINEConfiguration {
            get {
                return ResourceManager.GetString("OpenWINEConfiguration", resourceCulture);
            }
        }
        
        internal static string OpenWINEExplorer {
            get {
                return ResourceManager.GetString("OpenWINEExplorer", resourceCulture);
            }
        }
        
        internal static string KillAllWINEProcesses {
            get {
                return ResourceManager.GetString("KillAllWINEProcesses", resourceCulture);
            }
        }
        
        internal static string DisableGameoverlayRendererHack {
            get {
                return ResourceManager.GetString("DisableGameoverlayRendererHack", resourceCulture);
            }
        }
        
        internal static string DisableGameoverlayRendererHackDescription {
            get {
                return ResourceManager.GetString("DisableGameoverlayRendererHackDescription", resourceCulture);
            }
        }
        
        internal static string XModifiersHack {
            get {
                return ResourceManager.GetString("XModifiersHack", resourceCulture);
            }
        }
        
        internal static string XModifiersHackDescription {
            get {
                return ResourceManager.GetString("XModifiersHackDescription", resourceCulture);
            }
        }
        
        internal static string FixLibICUUCErrorHack {
            get {
                return ResourceManager.GetString("FixLibICUUCErrorHack", resourceCulture);
            }
        }
        
        internal static string FixLibICUUCErrorHackDescription {
            get {
                return ResourceManager.GetString("FixLibICUUCErrorHackDescription", resourceCulture);
            }
        }
        
        internal static string ForceLocaleHack {
            get {
                return ResourceManager.GetString("ForceLocaleHack", resourceCulture);
            }
        }
        
        internal static string ForceLocaleHackCUTF8 {
            get {
                return ResourceManager.GetString("ForceLocaleHackCUTF8", resourceCulture);
            }
        }
        
        internal static string ForceLocaleHackDescription {
            get {
                return ResourceManager.GetString("ForceLocaleHackDescription", resourceCulture);
            }
        }
        
        internal static string ForceLocaleHackUTFValidation {
            get {
                return ResourceManager.GetString("ForceLocaleHackUTFValidation", resourceCulture);
            }
        }
        
        internal static string ForceDontUseSystemTZ {
            get {
                return ResourceManager.GetString("ForceDontUseSystemTZ", resourceCulture);
            }
        }
        
        internal static string ForceDontUseSystemDescription {
            get {
                return ResourceManager.GetString("ForceDontUseSystemDescription", resourceCulture);
            }
        }
        
        internal static string TroubleshootingTitle {
            get {
                return ResourceManager.GetString("TroubleshootingTitle", resourceCulture);
            }
        }
        
        internal static string ClearWINEPrefixTroubleshooting {
            get {
                return ResourceManager.GetString("ClearWINEPrefixTroubleshooting", resourceCulture);
            }
        }
        
        internal static string ClearWINEPrefixTroubleshootingButton {
            get {
                return ResourceManager.GetString("ClearWINEPrefixTroubleshootingButton", resourceCulture);
            }
        }
        
        internal static string ClearManagedCompatToolsTroubleshooting {
            get {
                return ResourceManager.GetString("ClearManagedCompatToolsTroubleshooting", resourceCulture);
            }
        }
        
        internal static string ClearManagedCompatToolsTroubleshootingButton {
            get {
                return ResourceManager.GetString("ClearManagedCompatToolsTroubleshootingButton", resourceCulture);
            }
        }
        
        internal static string ClearDalamudTroubleshooting {
            get {
                return ResourceManager.GetString("ClearDalamudTroubleshooting", resourceCulture);
            }
        }
        
        internal static string ClearDalamudTroubleshootingButton {
            get {
                return ResourceManager.GetString("ClearDalamudTroubleshootingButton", resourceCulture);
            }
        }
        
        internal static string ClearAllLogsTroubleshooting {
            get {
                return ResourceManager.GetString("ClearAllLogsTroubleshooting", resourceCulture);
            }
        }
        
        internal static string ClearAllLogsTroubleshootingButton {
            get {
                return ResourceManager.GetString("ClearAllLogsTroubleshootingButton", resourceCulture);
            }
        }
        
        internal static string ResetSettingsTroubleshooting {
            get {
                return ResourceManager.GetString("ResetSettingsTroubleshooting", resourceCulture);
            }
        }
        
        internal static string ResetSettingsTroubleshootingButton {
            get {
                return ResourceManager.GetString("ResetSettingsTroubleshootingButton", resourceCulture);
            }
        }
        
        internal static string ResetAllTroubleshooting {
            get {
                return ResourceManager.GetString("ResetAllTroubleshooting", resourceCulture);
            }
        }
        
        internal static string GenerateTSPackTroubleshooting {
            get {
                return ResourceManager.GetString("GenerateTSPackTroubleshooting", resourceCulture);
            }
        }
        
        internal static string GenerateTSPackTroubleshootingButton {
            get {
                return ResourceManager.GetString("GenerateTSPackTroubleshootingButton", resourceCulture);
            }
        }
        
        internal static string ResetAllTroubleshootingButton {
            get {
                return ResourceManager.GetString("ResetAllTroubleshootingButton", resourceCulture);
            }
        }
        
        internal static string PatchPathSetting {
            get {
                return ResourceManager.GetString("PatchPathSetting", resourceCulture);
            }
        }
        
        internal static string PatchPathSettingDescription {
            get {
                return ResourceManager.GetString("PatchPathSettingDescription", resourceCulture);
            }
        }
        
        internal static string PatchPathSettingNotSetValidation {
            get {
                return ResourceManager.GetString("PatchPathSettingNotSetValidation", resourceCulture);
            }
        }
        
        internal static string PatchDownloadMethodSetting {
            get {
                return ResourceManager.GetString("PatchDownloadMethodSetting", resourceCulture);
            }
        }
        
        internal static string PatchDownloadMethodSettingDescription {
            get {
                return ResourceManager.GetString("PatchDownloadMethodSettingDescription", resourceCulture);
            }
        }
        
        internal static string MaximumSpeedSetting {
            get {
                return ResourceManager.GetString("MaximumSpeedSetting", resourceCulture);
            }
        }
        
        internal static string MaximumSpeedSettingDescription {
            get {
                return ResourceManager.GetString("MaximumSpeedSettingDescription", resourceCulture);
            }
        }
        
        internal static string KeepPatchesSetting {
            get {
                return ResourceManager.GetString("KeepPatchesSetting", resourceCulture);
            }
        }
        
        internal static string KeepPatchesSettingDescription {
            get {
                return ResourceManager.GetString("KeepPatchesSettingDescription", resourceCulture);
            }
        }
        
        internal static string PatchingTitle {
            get {
                return ResourceManager.GetString("PatchingTitle", resourceCulture);
            }
        }
        
        internal static string GamePathSetting {
            get {
                return ResourceManager.GetString("GamePathSetting", resourceCulture);
            }
        }
        
        internal static string GamePathSettingDescription {
            get {
                return ResourceManager.GetString("GamePathSettingDescription", resourceCulture);
            }
        }
        
        internal static string GamePathSettingNotSetValidation {
            get {
                return ResourceManager.GetString("GamePathSettingNotSetValidation", resourceCulture);
            }
        }
        
        internal static string GamePathSettingInvalidValidationj {
            get {
                return ResourceManager.GetString("GamePathSettingInvalidValidationj", resourceCulture);
            }
        }
        
        internal static string GameConfigurationPathSetting {
            get {
                return ResourceManager.GetString("GameConfigurationPathSetting", resourceCulture);
            }
        }
        
        internal static string GameConfigurationPathSettingDescription {
            get {
                return ResourceManager.GetString("GameConfigurationPathSettingDescription", resourceCulture);
            }
        }
        
        internal static string GameConfigurationPathNotSetValidation {
            get {
                return ResourceManager.GetString("GameConfigurationPathNotSetValidation", resourceCulture);
            }
        }
        
        internal static string AdditionalGameArgsSetting {
            get {
                return ResourceManager.GetString("AdditionalGameArgsSetting", resourceCulture);
            }
        }
        
        internal static string AdditionalGameArgsSettingDescription {
            get {
                return ResourceManager.GetString("AdditionalGameArgsSettingDescription", resourceCulture);
            }
        }
        
        internal static string GameLanguageSetting {
            get {
                return ResourceManager.GetString("GameLanguageSetting", resourceCulture);
            }
        }
        
        internal static string GameLanguageSettingDescription {
            get {
                return ResourceManager.GetString("GameLanguageSettingDescription", resourceCulture);
            }
        }
        
        internal static string GameDPIAwarenessSetting {
            get {
                return ResourceManager.GetString("GameDPIAwarenessSetting", resourceCulture);
            }
        }
        
        internal static string GameDPIAwarenessSettingDescription {
            get {
                return ResourceManager.GetString("GameDPIAwarenessSettingDescription", resourceCulture);
            }
        }
        
        internal static string UseXLAuthMacrosSetting {
            get {
                return ResourceManager.GetString("UseXLAuthMacrosSetting", resourceCulture);
            }
        }
        
        internal static string UseXLAuthMacrosSettingDescription {
            get {
                return ResourceManager.GetString("UseXLAuthMacrosSettingDescription", resourceCulture);
            }
        }
        
        internal static string IgnoreSteamSetting {
            get {
                return ResourceManager.GetString("IgnoreSteamSetting", resourceCulture);
            }
        }
        
        internal static string IgnoreSteamSettingDescription {
            get {
                return ResourceManager.GetString("IgnoreSteamSettingDescription", resourceCulture);
            }
        }
        
        internal static string UseUIDCacheSetting {
            get {
                return ResourceManager.GetString("UseUIDCacheSetting", resourceCulture);
            }
        }
        
        internal static string UseUIDCacheSettingDescription {
            get {
                return ResourceManager.GetString("UseUIDCacheSettingDescription", resourceCulture);
            }
        }
        
        internal static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        internal static string ResetUIDCacheInfo {
            get {
                return ResourceManager.GetString("ResetUIDCacheInfo", resourceCulture);
            }
        }
        
        internal static string ResetUIDCacheButton {
            get {
                return ResourceManager.GetString("ResetUIDCacheButton", resourceCulture);
            }
        }
        
        internal static string DebugTitle {
            get {
                return ResourceManager.GetString("DebugTitle", resourceCulture);
            }
        }
        
        internal static string DalamudTitle {
            get {
                return ResourceManager.GetString("DalamudTitle", resourceCulture);
            }
        }
        
        internal static string EnableDalamudSetting {
            get {
                return ResourceManager.GetString("EnableDalamudSetting", resourceCulture);
            }
        }
        
        internal static string EnableDalamudSettingDescription {
            get {
                return ResourceManager.GetString("EnableDalamudSettingDescription", resourceCulture);
            }
        }
        
        internal static string LoadMethodSetting {
            get {
                return ResourceManager.GetString("LoadMethodSetting", resourceCulture);
            }
        }
        
        internal static string LoadMethodSettingDescription {
            get {
                return ResourceManager.GetString("LoadMethodSettingDescription", resourceCulture);
            }
        }
        
        internal static string DalamudInjectionDelaySetting {
            get {
                return ResourceManager.GetString("DalamudInjectionDelaySetting", resourceCulture);
            }
        }
        
        internal static string DalamudInjectionDelaySettingDescription {
            get {
                return ResourceManager.GetString("DalamudInjectionDelaySettingDescription", resourceCulture);
            }
        }
        
        internal static string DalamudManualInjectionEnableSetting {
            get {
                return ResourceManager.GetString("DalamudManualInjectionEnableSetting", resourceCulture);
            }
        }
        
        internal static string DalamudManualInjectionEnableSettingDescription {
            get {
                return ResourceManager.GetString("DalamudManualInjectionEnableSettingDescription", resourceCulture);
            }
        }
        
        internal static string DalamudLocalInjectionPathSetting {
            get {
                return ResourceManager.GetString("DalamudLocalInjectionPathSetting", resourceCulture);
            }
        }
        
        internal static string DalamudLocalInjectionPathSettingDescription {
            get {
                return ResourceManager.GetString("DalamudLocalInjectionPathSettingDescription", resourceCulture);
            }
        }
        
        internal static string DalamudLocalInjectionPathSettingNoDirValidation {
            get {
                return ResourceManager.GetString("DalamudLocalInjectionPathSettingNoDirValidation", resourceCulture);
            }
        }
        
        internal static string DalamudLocalInjectionPathSettingNoInjValidation {
            get {
                return ResourceManager.GetString("DalamudLocalInjectionPathSettingNoInjValidation", resourceCulture);
            }
        }
        
        internal static string OpenRepositoryButton {
            get {
                return ResourceManager.GetString("OpenRepositoryButton", resourceCulture);
            }
        }
        
        internal static string JoinDiscordButton {
            get {
                return ResourceManager.GetString("JoinDiscordButton", resourceCulture);
            }
        }
        
        internal static string SeeSoftwareLicensesButton {
            get {
                return ResourceManager.GetString("SeeSoftwareLicensesButton", resourceCulture);
            }
        }
        
        internal static string XLCoreCreatedBy {
            get {
                return ResourceManager.GetString("XLCoreCreatedBy", resourceCulture);
            }
        }
        
        internal static string NewsCaption {
            get {
                return ResourceManager.GetString("NewsCaption", resourceCulture);
            }
        }
        
        internal static string TopicsCaption {
            get {
                return ResourceManager.GetString("TopicsCaption", resourceCulture);
            }
        }
        
        internal static string NewsLoading {
            get {
                return ResourceManager.GetString("NewsLoading", resourceCulture);
            }
        }
        
        internal static string XLElevatedWarning {
            get {
                return ResourceManager.GetString("XLElevatedWarning", resourceCulture);
            }
        }
        
        internal static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        internal static string RepairOfficialLauncherOpenError {
            get {
                return ResourceManager.GetString("RepairOfficialLauncherOpenError", resourceCulture);
            }
        }
        
        internal static string XIVLauncherError {
            get {
                return ResourceManager.GetString("XIVLauncherError", resourceCulture);
            }
        }
        
        internal static string ReinstallUIDCacheError {
            get {
                return ResourceManager.GetString("ReinstallUIDCacheError", resourceCulture);
            }
        }
        
        internal static string LoginNoServiceAccountError {
            get {
                return ResourceManager.GetString("LoginNoServiceAccountError", resourceCulture);
            }
        }
        
        internal static string LoginTermsNotAcceptedError {
            get {
                return ResourceManager.GetString("LoginTermsNotAcceptedError", resourceCulture);
            }
        }
        
        internal static string UpdateCheckFinished {
            get {
                return ResourceManager.GetString("UpdateCheckFinished", resourceCulture);
            }
        }
        
        internal static string WaitingForDalamud {
            get {
                return ResourceManager.GetString("WaitingForDalamud", resourceCulture);
            }
        }
        
        internal static string PleaseBePatient {
            get {
                return ResourceManager.GetString("PleaseBePatient", resourceCulture);
            }
        }
        
        internal static string DisableAutoLoginButton {
            get {
                return ResourceManager.GetString("DisableAutoLoginButton", resourceCulture);
            }
        }
        
        internal static string AutoLoginDisabledNextStart {
            get {
                return ResourceManager.GetString("AutoLoginDisabledNextStart", resourceCulture);
            }
        }
        
        internal static string NoSavedAccounts {
            get {
                return ResourceManager.GetString("NoSavedAccounts", resourceCulture);
            }
        }
        
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        internal static string ServiceStatus {
            get {
                return ResourceManager.GetString("ServiceStatus", resourceCulture);
            }
        }
        
        internal static string LauncherSettings {
            get {
                return ResourceManager.GetString("LauncherSettings", resourceCulture);
            }
        }
        
        internal static string UsernameInput {
            get {
                return ResourceManager.GetString("UsernameInput", resourceCulture);
            }
        }
        
        internal static string UsernameInputHint {
            get {
                return ResourceManager.GetString("UsernameInputHint", resourceCulture);
            }
        }
        
        internal static string PasswordInput {
            get {
                return ResourceManager.GetString("PasswordInput", resourceCulture);
            }
        }
        
        internal static string PasswordInputHint {
            get {
                return ResourceManager.GetString("PasswordInputHint", resourceCulture);
            }
        }
        
        internal static string UseOneTimePasswordCheckbox {
            get {
                return ResourceManager.GetString("UseOneTimePasswordCheckbox", resourceCulture);
            }
        }
        
        internal static string UseSteamServiceAccount {
            get {
                return ResourceManager.GetString("UseSteamServiceAccount", resourceCulture);
            }
        }
        
        internal static string FreeTrialAccountCheckbox {
            get {
                return ResourceManager.GetString("FreeTrialAccountCheckbox", resourceCulture);
            }
        }
        
        internal static string LogInAutomaticCheckbox {
            get {
                return ResourceManager.GetString("LogInAutomaticCheckbox", resourceCulture);
            }
        }
        
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        internal static string LaunchWithoutDalamudButton {
            get {
                return ResourceManager.GetString("LaunchWithoutDalamudButton", resourceCulture);
            }
        }
        
        internal static string LaunchWithoutPluginsButton {
            get {
                return ResourceManager.GetString("LaunchWithoutPluginsButton", resourceCulture);
            }
        }
        
        internal static string LaunchWithNoCustomPluginsButton {
            get {
                return ResourceManager.GetString("LaunchWithNoCustomPluginsButton", resourceCulture);
            }
        }
        
        internal static string PatchWithoutLaunchingButton {
            get {
                return ResourceManager.GetString("PatchWithoutLaunchingButton", resourceCulture);
            }
        }
        
        internal static string RepairGameFilesButton {
            get {
                return ResourceManager.GetString("RepairGameFilesButton", resourceCulture);
            }
        }
        
        internal static string NoSecretsProviderWarning {
            get {
                return ResourceManager.GetString("NoSecretsProviderWarning", resourceCulture);
            }
        }
        
        internal static string TroubleshootingDestructiveActionWarning {
            get {
                return ResourceManager.GetString("TroubleshootingDestructiveActionWarning", resourceCulture);
            }
        }
        
        internal static string PreparingForCompatTool {
            get {
                return ResourceManager.GetString("PreparingForCompatTool", resourceCulture);
            }
        }
        
        internal static string StartingGame {
            get {
                return ResourceManager.GetString("StartingGame", resourceCulture);
            }
        }
        
        internal static string HaveFun {
            get {
                return ResourceManager.GetString("HaveFun", resourceCulture);
            }
        }
        
        internal static string CannotGetBootVerError {
            get {
                return ResourceManager.GetString("CannotGetBootVerError", resourceCulture);
            }
        }
        
        internal static string CannotPatchGameOpenError {
            get {
                return ResourceManager.GetString("CannotPatchGameOpenError", resourceCulture);
            }
        }
        
        internal static string NowPatching {
            get {
                return ResourceManager.GetString("NowPatching", resourceCulture);
            }
        }
        
        internal static string WorkingOnStatus {
            get {
                return ResourceManager.GetString("WorkingOnStatus", resourceCulture);
            }
        }
        
        internal static string LeftToDownloadStatus {
            get {
                return ResourceManager.GetString("LeftToDownloadStatus", resourceCulture);
            }
        }
        
        internal static string NotEnoughSpacePatchesError {
            get {
                return ResourceManager.GetString("NotEnoughSpacePatchesError", resourceCulture);
            }
        }
        
        internal static string PatchInstallerStartFailError {
            get {
                return ResourceManager.GetString("PatchInstallerStartFailError", resourceCulture);
            }
        }
        
        internal static string NotEnoughSpaceAllPatchesError {
            get {
                return ResourceManager.GetString("NotEnoughSpaceAllPatchesError", resourceCulture);
            }
        }
        
        internal static string NotEnoughSpaceGameError {
            get {
                return ResourceManager.GetString("NotEnoughSpaceGameError", resourceCulture);
            }
        }
        
        internal static string CannotVerifyGameFilesError {
            get {
                return ResourceManager.GetString("CannotVerifyGameFilesError", resourceCulture);
            }
        }
        
        internal static string PatchInstallerGenericError {
            get {
                return ResourceManager.GetString("PatchInstallerGenericError", resourceCulture);
            }
        }
        
        internal static string NowRepairingFiles {
            get {
                return ResourceManager.GetString("NowRepairingFiles", resourceCulture);
            }
        }
        
        internal static string RepairAllFilesValid {
            get {
                return ResourceManager.GetString("RepairAllFilesValid", resourceCulture);
            }
        }
        
        internal static string RepairFixedSingularFile {
            get {
                return ResourceManager.GetString("RepairFixedSingularFile", resourceCulture);
            }
        }
        
        internal static string RepairFixedPluralFiles {
            get {
                return ResourceManager.GetString("RepairFixedPluralFiles", resourceCulture);
            }
        }
        
        internal static string RepairSingleFileMoved {
            get {
                return ResourceManager.GetString("RepairSingleFileMoved", resourceCulture);
            }
        }
        
        internal static string RepairPluralFilesMoved {
            get {
                return ResourceManager.GetString("RepairPluralFilesMoved", resourceCulture);
            }
        }
        
        internal static string RepairGameVerUnsupportedError {
            get {
                return ResourceManager.GetString("RepairGameVerUnsupportedError", resourceCulture);
            }
        }
        
        internal static string RepairFailureError {
            get {
                return ResourceManager.GetString("RepairFailureError", resourceCulture);
            }
        }
    }
}
