name: "Nuget Dependencies"

on:
  workflow_dispatch:

jobs:
  Generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Python3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Setup Flatpak
        run: |
          sudo apt update -y
          sudo apt install flatpak -y
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo 
          flatpak install --user org.freedesktop.Sdk.Extension.dotnet8/x86_64/24.08 -y # Update this when needed.
          flatpak install --user org.freedesktop.Sdk/x86_64/24.08 -y # As well as this, if dependency generation is failing.

      - name: Generate nuget-dependencies.json
        working-directory: ./src/XIVLauncher.Core/
        run: |
          curl -LO https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/master/dotnet/flatpak-dotnet-generator.py
          python3 flatpak-dotnet-generator.py --dotnet 8 --freedesktop 24.08 nuget-dependencies.json XIVLauncher.Core.csproj

      - name: Upload nuget-dependencies.json
        uses: actions/upload-artifact@v4
        with:
          name: nuget-dependencies
          path: |
            ./src/XIVLauncher.Core/nuget-dependencies.json
